### PR TITLE
Ff4j store couchbase

### PR DESCRIPTION
**Pull request by jackpf**

### CODE REVIEW

**Comment by jackpf** [comment]
I've noticed the build has failed - the tests require a connection to couchbase to run unfortunately.
I experimented with [CouchbaseMock](https://github.com/couchbase/CouchbaseMock) but didn't manage to get it to work successfully. I could spend a bit more time looking into it if you like

**Comment by clun** [comment]
I will merge in 24H nevertheless and look into it. So as you wish. It seems indeed the embedded CouchBase on 8091 is unreachable.

**Comment by jackpf** [comment]
Cool - Ive ran the tests locally and they all pass.
I'm going to spend a bit of time seeing if i can get couchbasemock to work, i'll let you know if i have any success

**Comment by clun** [comment]
Will check today to fix tests

**Comment by jackpf** [comment]
So the problem is that it requires an external couchbase connection, as I've not found a well supported mock/in memory couchbase package to use.

The way I've been running tests is having a couchbase instance booted in Docker, however I don't know how well this will suit your build pipeline.

Let me know if you need any help!

**Comment by clun** [comment]
I pulled the component. I am doing little refactoring & checking the test part, news very soon

**Pull request merged**
