### PR TITLE
squid:S1214 - Constants should not be defined in interfaces

### PR DESCRIPTION
**Pull request by georgekankava**
This pull request is focused on resolving occurrences of Sonar rules
squid:S1214 - Constants should not be defined in interfaces.
squid:S1118 - Utility classes should not have public constructors.
You can find more information about the issues here:
https://dev.eclipse.org/sonar/rules/show/squid:S1214
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
George Kankava

### CODE REVIEW

**Comment by clun** [comment]
Hi George,

I have some questions about this one. I think that declaring constants into interfaces is great idea because this way you can implement the interface and reuse the constants !!!

**Comment by bjohnso5** [comment]
See [here](https://en.wikipedia.org/wiki/Constant_interface) for some information regarding the constant interface anti-pattern. In this case, it would be better to modify that constants interface into a class with only public static members that has a private constructor. It allows the same sharing of constants without each class needing to explicitly "implement" an interface.

**Comment by georgekankava** [comment]
Hi Cédrick,

I agree with @bjohnso5 but if you prefer to use this way sure we can leave it.

**Comment by clun** [comment]
Wikipedia gives a lot of details to understand reasons why this is an anti-patterns. Most of them are pretty weak except last one : 

_Unless a developer checks any implemented interfaces when adding a constant to a class, or does so but makes a typo in the new constant's name, the value of a constant can be silently _changed._

I'm still not 100% happy because i liked the little trick with constant interfaces. Nevertheless no COMPROMISE FOR QUALITY : I merge the PR, thank for making all of us progressing.

**Pull request merged**
