### PR TITLE
Added region identifier element to the base schema and related changes

### PR DESCRIPTION
**Pull request by alladivasu**
JdbcFeatureStoreConstants
-Added bunch of constants for region and group based queries
-UID to FEATURE_NAME
-ENABLE to FATURE_VALUE
FeatureStoreSpringJdbc
- Modified column names
-Added region identifier logic all over
-Read, create, delete, check if exists and update operations addition for region
 
Feature
-Added region identifier
-Added constructor for region based initialization 
 
AbstractStoreTest
-changed tests according to store changes
AssertFf4j
--changed tests according to store changes
FeatureXmlParser
-Added region identifier and fixed feature xml defect
FeatureJsonMarshaller
-         Added marshall and unmarshall logic for region identifier
 
ParameterUtils
-         Fixed some sev1 sonar violation
JdbcFeatureStore
- Modified column names
-Added region identifier logic all over
-Read, create, delete, check if exists and update operations addition for region

MongoDB changes:
-modified object mapper and builder and store classes to incorporate region identifier changes

### CODE REVIEW

**Comment by alladivasu** [comment]
Hi Cédrick, could you please let me know how do you want proceed on this pull request, do you want me to contribute to the other project here? Did you get chance to see the code changes?

**Comment by clun** [comment]
Hi Alladivasu,

Thank you for your work.

I will use your modifications in the next release of FF4J (1.3.1). Still, you updates are impactful for me. 
So far the features hadn't their own fields. You expecte me to add the region code - which is a good idea - but 
soon another company would rather want to add other fields and change the datamodel again. 

I would like to find a solution to code this once. I propose to create a "customField" map in the Feature Class :  anyone could declare custom fields or extend the featureClass.

**Comment by clun** [comment]
I started to enhance features and allow custom properties like the sample below : 

```
<feature uid="first" enable="true" description="description" >
 <security>
   <role name="USER" />
 </security>
 <properties>
   <property name="regionIdentifier" value="AMER" />
   <property name="ppint" 	  value="12"   />
   <property name="ppdouble"   value="12.5" />
   <property name="ppboolean"  value="true" />
   <property name="ppstring"   value="hello" />
   <property name="ppListInt"  value="12,13,14" />
   <property name="myLogLevel" value="DEBUG" type="org.ff4j.property.PropertyLogLevel" />
  </properties>
</feature>
```
This way you could add any new property without changing the JDBC Data model, ff4j will handle it for you.

**Comment by alladivasu** [comment]
I will wait for version 1.4, thank you for looking into this idea and hope this implementation approach is efficient.

**Pull request closed without merging**
